[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/index"
  to = "/.index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200