export const currency = [
   { code: 'UAH', name: '🇺🇦 Гривна' },
    { code: 'EUR', name: '🇪🇺 Евро' },
    { code: 'GBP', name: '🇬🇧 Фунт стерлингов' },
    { code: 'PLN', name: '🇵🇱 Злотый' },
    { code: 'DKK', name: '🇩🇰 Датская крона' },
    { code: 'SEK', name: '🇸🇪 Шведская крона' },
    { code: 'CZK', name: '🇨🇿 Чешская крона' },
    { code: 'RON', name: '🇷🇴 Румынский лей' },
    { code: 'CAD', name: '🇨🇦 Канадский доллар' },
    { code: 'AUD', name: '🇦🇺 Австралийский доллар' },
    { code: 'NZD', name: '🇳🇿 Новозеландский долар' },
    { code: 'TRY', name: '🇹🇷 Лира' },
    { code: 'AZN', name: '🇦🇿 Манат' },
    { code: 'UZS', name: '🇺🇿 Сом' },
    { code: 'KZT', name: '🇰🇿 Казахский Тенге' },
    { code: 'KRW', name: '🇰🇷 Вона' },
    { code: 'MYR', name: '🇲🇾 Малайский Ринггит' },
    { code: 'INR', name: '🇮🇳 Рупия' },
    { code: 'BDT', name: '🇧🇩 Бангладешская така' },
    { code: 'LKR', name: '🇱🇰 Шри-ланкийская рупия' },
    { code: 'PKR', name: '🇵🇰 Пакистанская рупия' },
    { code: 'IQD', name: '🇮🇶 Иракский динар' },
    { code: 'EGP', name: '🇪🇬 Египетский фунт' },
    { code: 'CLP', name: '🇨🇱 Чилийское Песо' },
    { code: 'BRL', name: '🇧🇷 Реал' },
    { code: 'MXN', name: '🇲🇽 Мексиканское песо' },
    { code: 'RUB', name: '🇦🇷 Аргентинское песо' },
    { code: 'ZAR', name: '🇿🇦 Южноафриканский рэнд' },
    { code: 'XOF', name: '🇨🇮 Западноафриканский франк' }
];